services:
  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: peercast
      TZ: Asia/Tokyo
    command: --default-time-zone=+09:00
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    container_name: peercast-0yp-mariadb

volumes:
  mariadb_data:
